---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags: tools

- name: install aptitude
  apt: pkg=aptitude state=present

- name: upgrade packages
  apt: upgrade=safe
  tags: util

- name: install apt-transport-https
  apt: pkg=apt-transport-https state=present force=yes
  tags: util

- name: install locales
  apt: pkg=locales state=present

- name: install htop
  apt: pkg=htop state=present

- name: install sudo
  apt: pkg=sudo state=present

- name: install curl
  apt: pkg=curl state=present

- name: install rsync
  apt: pkg=rsync state=present

- name: install screen
  apt: pkg=screen state=present

- name: install ntp
  apt: pkg=ntp state=present

- name: install git
  apt: pkg=git state=present

- name: install multitail
  apt: pkg=multitail state=present

- name: install ca-certificates
  apt: pkg=ca-certificates state=present


# python
- name: install python-setuptools
  apt: pkg=python-setuptools state=present

- name: install pip
  easy_install: name=pip

- name: install virtualenv
  easy_install: name=virtualenv



